export const NAV_LINKS = [
  { href: '#about', label: 'About' },
  { href: '#portfolio', label: 'Portfolio' },
  { href: '#services', label: 'Services' },
]

export const PORTFOLIO_IMAGES = [
    {
      id: 1,
      src: '/images/portfolio/darya-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/darya-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 2,
      src: '/images/portfolio/darya-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/darya-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 3,
      src: '/images/portfolio/darya-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/darya-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 4,
      src: '/images/portfolio/darya-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/darya-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 5,
      src: '/images/portfolio/elina-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/elina-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 6,
      src: '/images/portfolio/elina-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/elina-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 7,
      src: '/images/portfolio/elina-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/elina-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 8,
      src: '/images/portfolio/elina-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/elina-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 9,
      src: '/images/portfolio/liza-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/liza-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 10,
      src: '/images/portfolio/liza-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/liza-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 11,
      src: '/images/portfolio/liza-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/liza-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 12,
      src: '/images/portfolio/liza-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/liza-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 13,
      src: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 14,
      src: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 15,
      src: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 16,
      src: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/veronika-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 17,
      src: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 18,
      src: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 19,
      src: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 20,
      src: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/tanya-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 21,
      src: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 22,
      src: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 23,
      src: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 24,
      src: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-4.jpg',
      thumbnail: '/images/portfolio/svetlana-fotosessiya-makiyazh-2026-4.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 25,
      src: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 26,
      src: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 27,
      src: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/dilyara-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 28,
      src: '/images/portfolio/irina-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/irina-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 29,
      src: '/images/portfolio/irina-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/irina-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 30,
      src: '/images/portfolio/irina-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/irina-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 31,
      src: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 32,
      src: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 33,
      src: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/evelina-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 34,
      src: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 35,
      src: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 36,
      src: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/parnaya-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 37,
      src: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 38,
      src: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 39,
      src: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/anastasia-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 40,
      src: '/images/portfolio/julia-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/julia-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 41,
      src: '/images/portfolio/julia-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/julia-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 42,
      src: '/images/portfolio/julia-fotosessiya-makiyazh-2026-3.jpg',
      thumbnail: '/images/portfolio/julia-fotosessiya-makiyazh-2026-3.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 43,
      src: '/images/portfolio/vlada-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/vlada-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 44,
      src: '/images/portfolio/vlada-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/vlada-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 45,
      src: '/images/portfolio/olya-fotosessiya-makiyazh-2026-1.jpg',
      thumbnail: '/images/portfolio/olya-fotosessiya-makiyazh-2026-1.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
    {
      id: 46,
      src: '/images/portfolio/olya-fotosessiya-makiyazh-2026-2.jpg',
      thumbnail: '/images/portfolio/olya-fotosessiya-makiyazh-2026-2.jpg',
      alt: 'Профессиональный макияж для фотосессии от визажиста. Работа с моделью, создание образа.',
    },
]

export const PORTFOLIO_BRANDS_IMAGES = [
    {
      id: 1,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-1.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-1.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 2,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-2.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-2.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 3,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-3.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-3.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 4,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-4.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-4.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 5,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-5.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-5.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 6,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-6.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-6.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 7,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-7.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-7.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 8,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-8.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-8.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 9,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-9.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-9.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 10,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-10.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-10.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 11,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-11.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-11.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 12,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-12.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-12.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 13,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-13.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-13.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 14,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-14.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-14.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 15,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-15.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-15.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 16,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-16.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-16.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    },
    {
      id: 17,
      src: '/images/portfolio/brands/sotrudnichestvo-s-brendom-17.jpg',
      thumbnail: '/images/portfolio/brands/sotrudnichestvo-s-brendom-17.jpg',
      alt: 'Работа визажиста для бьюти-бренда. Создание коммерческого образа для съемки каталога.',
    }
];

export const CREATIVE_PROCESS_IMAGES = [
  'https://images.unsplash.com/photo-1677083971428-d882ae2b42a1?auto=format&fit=crop&w=1200&q=50',
  'https://images.unsplash.com/photo-1766879240581-ce4a7e91f92e?auto=format&fit=crop&w=1200&q=50',
  'https://images.unsplash.com/photo-1628157850970-7424f0d29586?auto=format&fit=crop&w=1200&q=50',
  'https://images.unsplash.com/photo-1770533868567-1dfb76ce578c?auto=format&fit=crop&w=1200&q=50',
]
